// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD461nschfwSsJK9iP2Thsy9HVzcpDpCE0',
    appId: '1:1014089483841:web:b95b50fe2f2ae8278ce8c0',
    messagingSenderId: '1014089483841',
    projectId: 'fir-confige-6bdce',
    authDomain: 'fir-confige-6bdce.firebaseapp.com',
    storageBucket: 'fir-confige-6bdce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT7t3luoP4nsTYrOVf9WrLeR1IsUcsqlc',
    appId: '1:1014089483841:android:ef47e6195487f7108ce8c0',
    messagingSenderId: '1014089483841',
    projectId: 'fir-confige-6bdce',
    storageBucket: 'fir-confige-6bdce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAys7q2JZb2sJ-xGKbJDkCw2uDBw8s9a5k',
    appId: '1:1014089483841:ios:7b4d62f1ff7ff7a58ce8c0',
    messagingSenderId: '1014089483841',
    projectId: 'fir-confige-6bdce',
    storageBucket: 'fir-confige-6bdce.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAys7q2JZb2sJ-xGKbJDkCw2uDBw8s9a5k',
    appId: '1:1014089483841:ios:7b4d62f1ff7ff7a58ce8c0',
    messagingSenderId: '1014089483841',
    projectId: 'fir-confige-6bdce',
    storageBucket: 'fir-confige-6bdce.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD461nschfwSsJK9iP2Thsy9HVzcpDpCE0',
    appId: '1:1014089483841:web:385c4e08090b14a28ce8c0',
    messagingSenderId: '1014089483841',
    projectId: 'fir-confige-6bdce',
    authDomain: 'fir-confige-6bdce.firebaseapp.com',
    storageBucket: 'fir-confige-6bdce.appspot.com',
  );
}
